const Errors = {
  USER_ERROR: 'USER_ERROR',
  USER_FORBIDDEN: 'USER_FORBIDDEN',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USERNAME_OR_PASSWORD_INVALID: 'USERNAME_OR_PASSWORD_INVALID',
  INVITATION_CODE_INVALID: 'INVITATION_CODE_INVALID',
  EMAIL_INVALID: 'EMAIL_INVALID',

  ALREADY_EXISTS: 'ALREADY_EXISTS',

  TARIFF_INVALID: 'TARIFF_INVALID',

  SIMPLE_SCHEDULER_ERROR: 'SIMPLE_SCHEDULER_ERROR',
};

export default Errors;
